[package]
name = "StableHorder"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = '0.7.3'
reqwest = { version = '0.11.14', features = ["json", "socks"] }
tokio = { version = "1.26.0", features = ["full"] }
serde = { version = '1.0.156', features = ["derive"] }
serde_json = '1.0.94'